<?php

require_once dirname(__FILE__) . '/../../../../app/components/NController.php';

/**
 * Test class for NController.
 * Generated by PHPUnit on 2011-02-28 at 16:48:32.
 */
class NControllerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var NController
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new NController;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
