<?php
require_once dirname(__FILE__) . '/../../../../app/components/NFileManager.php';
/**
 * Test class for NFileManager.
 * Generated by PHPUnit on 2011-03-10 at 11:11:22.
 */
class NFileManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var NFileManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new NFileManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	
	public function testaddFile(){

	// 3) Sending it file contents and a name
	$test = $this->object->addFile('tesjhgfsjfhgd','test');
	$this->assertInt($test);

	// Checks to see if the file has been created as a result of test 3

	// Checks the contents of test3's file.

	// 4) Sends the item contents,name and a custom mime type.
	$properties = array('mime'=>'image/jpg');
	$test = $this->object->addFile('tesjhgfsjfhgd','test',$properties);
	$this->assertInt($test);

	// Checks to see if the file has been created as a result of test 4.

	//Checks the contents of test4's file.
	

	//addFile($fileContents,$fileName,array(''))

	}

	/**
	 * @todo Implement testSaveUploadedFile().
	 */
	public function testSaveUploadedFile() {
		//Pass it nothing
		$test = $this->object->SaveUploadedFile();
		$this->assertNull($test);

		//Pass it something which is not a file
		$test = $this->object->SaveUploadedFile(2);
		$this->assertNull($test);

		//Pass it something which is encoded in base 64 and check to see that it returns an id of a record in the database.
		

		//pass a file. Check to see that the and check to see that it returns an id of a record in the database.
		$this->assertFileExists('/path/to/file');

		//Makes sure a file exists in the correct location.
	}

	function testGetFile(){

				// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
		//Pass it nothing
		//$test = $this->object->testGetFile();
		//$this->assertFalse($test);

		//Pass it something which is not an array
	}

}

?>
